services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=false
      - http_proxy=http://localhost:8080
      - https_proxy=http://localhost:8080
    command: ["/workspace/venv/bin/streamlit", "run", "streamlit_app.py"]